GET http://localhost:3000/login
Content-Type: application/json

{
    "email": "super@gmail.com",
    "password": "123"
}


###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "Superman",
    "email": "super@gmail.com",
    "password": "123",
    "preference": []
}

###

POST http://localhost:3000/preference
Content-Type: application/json

{
    "email": "super@gmail.com",
    "preference": ["natural", "historical"]
}